services:
    postgres:
        image: postgres:15.2
        restart: always
        volumes:
            - stats-space-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: stats-space-db

volumes:
    stats-space-data:
